//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookCenter.DataBase
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BookCenterDBEntities1 : DbContext
    {
        public BookCenterDBEntities1()
            : base("name=BookCenterDBEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<TBLBookRental> TBLBookRental { get; set; }
        public virtual DbSet<TBLSafetyBook> TBLSafetyBook { get; set; }
        public virtual DbSet<TBLUserLog> TBLUserLog { get; set; }
        public virtual DbSet<TBLBookList> TBLBookList { get; set; }
        public virtual DbSet<TBLReaderStudent> TBLReaderStudent { get; set; }
    }
}
