//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookCenter.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLBookList
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public string WriterName { get; set; }
        public string Publisher { get; set; }
        public string Category { get; set; }
        public Nullable<System.DateTime> ReleaseDate { get; set; }
        public Nullable<int> Stock { get; set; }
        public string Images { get; set; }
    }
}
