//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookCenter.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLReaderStudent
    {
        public int ID { get; set; }
        public string NationalNo { get; set; }
        public string Name { get; set; }
        public string Surname { get; set; }
        public string ClassNo { get; set; }
        public Nullable<System.DateTime> DateBirth { get; set; }
        public string Telephone { get; set; }
        public string Email { get; set; }
        public Nullable<System.DateTime> MembershipDate { get; set; }
        public string Gender { get; set; }
        public string Address { get; set; }
        public string Images { get; set; }
    }
}
