//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookCenter.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLUserLog
    {
        public int ID { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public string Authorize { get; set; }
    }
}
